[build]
  # If your files are in a subfolder, specify it here
  # base = "/"  # Use this if files are in root
  # base = "a"  # Use this if files are in a folder called "a"
  command = "echo 'No build command needed'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
